name: CD Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    container:
      image: ci-image:3.0

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          CD_SSH_KEY: ${{ secrets.CD_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          printf '%s\n' "$CD_SSH_KEY" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan 192.168.0.180 >> ~/.ssh/known_hosts
          ssh-keyscan 192.168.0.181 >> ~/.ssh/known_hosts
          ssh-keyscan 192.168.0.182 >> ~/.ssh/known_hosts

      - name: Deploy Infrastructure
        run: |
          ansible-playbook \
            -i ansible/inventory/homelab.ini \
            ansible/playbooks/cd-deploy.yml
