name: Pipeline Test

on:
  push:

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    container:
      image: node:22-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Show Environment
        run: |
          node --version
          git --version
          pwd
          ls -la

      - name: Find Compose Files
        run: |
          find . -name "compose.yaml"
