name: Pipeline Compose & Syntax Check

on:
  push:

jobs:
 validate-compose:
    runs-on: ubuntu-latest

    container:
      image: ci-image:3.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Environment
        run: |
          echo "===== Environment ====="
          node --version
          git --version
          pwd
          ls -la

      - name: Validate Docker Compose Stacks
        run: |
          set -e

          echo ""
          echo "===== Docker Compose Validation ====="

          find . -name "compose.yaml" | while read composefile
          do
            stackdir=$(dirname "$composefile")

            echo ""
            echo "======================================"
            echo "Checking Stack:"
            echo "$stackdir"
            echo "======================================"

            (
              cd "$stackdir"

              docker compose config > /dev/null
            )

            echo "SUCCESS: $stackdir"
          done

          echo ""
          echo "All Docker Compose files are valid."

      - name: Validate Ansible playbooks
        run: |
          set -e

          echo ""
          echo "===== Docker Compose Validation ====="

          for playbook in *.yml
          do
              echo "Checking $playbook"

              ansible-playbook \
              --syntax-check \
              "$playbook"

          done
          echo ""
          echo "All Docker Compose files are valid."