services: 
  nginx-webserver:
    image: nginx
    networks:
     - homelab-net
    ports:
     - 80:80
    volumes:
     - /home/renatubuntu/documentation/nginx-config/default.conf:/etc/nginx/conf.d/default.conf
     - /home/renatubuntu/documentation/Webserver:/usr/share/nginx/html
    restart: unless-stopped

  grafana-web:
    image: grafana/grafana
    networks:
     - homelab-net
    ports:
     - 3000:3000
    volumes:
     - /home/renatubuntu/documentation/grafanafiles:/var/lib/grafana
    restart: unless-stopped

  prometheus-data:
    image: prom/prometheus
    networks:
     - homelab-net
    ports:
     - 9090:9090
    volumes:
     - /home/renatubuntu/documentation/prometheus-data:/prometheus
     - /home/renatubuntu/documentation/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter

    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    networks:
      - homelab-net

    ports:
      - 9100:9100

    restart: unless-stopped

  cadvisor:
    image: google/cadvisor

    ports:
      - 8080:8080

    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

    networks:
      - homelab-net

    restart: unless-stopped
networks:
  homelab-net:
