---
- name: Synchronize servers with main
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Fetch latest changes from origin
      ansible.builtin.command:
        cmd: git fetch origin
        chdir: "{{ repository_path }}"

    - name: Reset working tree to origin/main
      ansible.builtin.command:
        cmd: git reset --hard origin/main
        chdir: "{{ repository_path }}"
