---
- name: Deploy Gitea .env
  hosts: nonprod
  become: false

  tasks:
    - name: Deploy Gitea .env
      ansible.builtin.template:
        src: "{{ templates.gitea.path }}/.env.example.j2"
        dest: "{{ repository_path }}/git-platform/.env.example"
        mode: "0600"
