---
- name: Variablen anzeigen
  hosts: dev
  gather_facts: false

  tasks:
    - name: Zeige Variablen
      ansible.builtin.debug:
        msg:
          - "ansible_user = {{ ansible_user }}"
          - "git_repository = {{ git_repository }}"
          - "git_branch = {{ git_branch }}"
          - "repository_directory = {{ repository_directory }}"