services: 
  grafana-web:
    image: grafana/grafana
    networks:
     - homelab-net
     - reverse-proxy-net
    ports:
     - 3000:3000
    volumes:
     - ./grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus-data:
    image: prom/prometheus
    networks:
     - homelab-net
    ports:
     - 9090:9090
    volumes:
     - ./prometheus-data:/prometheus
     - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter

    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    networks:
      - homelab-net

    ports:
      - 9100:9100

    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor

    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

    ports:
      - "8080:8080"

    restart: unless-stopped

    networks:
      - homelab-net
      - reverse-proxy-net
   
networks:
  homelab-net:
  reverse-proxy-net:
    external: true
