docker:

  networks:

    - name: reverse-proxy-net
      state: present

    - name: homelab-net
      state: present

  images:

    - name: ci-image
      tag: "3.0"
      context: "{{ repository_path }}/Dockerfiles/ci-image"
      dockerfile: Dockerfile
      rebuild: always

    - name: renat-nginx
      tag: "v2"
      context: "{{ repository_path }}/Dockerfiles/nginx-image"
      dockerfile: Dockerfile