services:
  reverse-proxy:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - /home/renatubuntu/documentation/reverse-proxy/nginx-config:/etc/nginx/conf.d
    networks:
     - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true
