services:
  reverse-proxy:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx-config:/etc/nginx/conf.d
    networks:
     - reverse-proxy-net
    restart: unless-stopped

networks:
  reverse-proxy-net:
    external: true
