services:
  mariadb-datenbank:
    image: mariadb
    environment:
     -  MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
     -  MARIADB_DATABASE=${MARIADB_DATABASE}
     -  MARIADB_USER=${MARIADB_USER}
     -  MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
     - "3306:3306"
    volumes:
     - ./bookstack-mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
     - homelab-net

  bookstack-app:
   image: linuxserver/bookstack
   environment:
    - PUID=1000
    - PGID=1000 
    -  APP_URL=${APP_URL}
    -  APP_KEY=${APP_KEY}
    - DB_HOST=${DB_HOST}
    - DB_DATABASE=${DB_DATABASE}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_PORT=${DB_PORT}
   ports:
    - "6875:80"
   volumes:
    - ./bookstack-app:/config
   restart: unless-stopped
   networks:
    - homelab-net
    - reverse-proxy-net

networks:
  homelab-net:
  reverse-proxy-net:
    external: true    
